name: riddimfutar
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: any
  location: ^3.0.0
  http: any
  flutter_statusbarcolor: any
  throttling: any
  audioplayers: ^0.15.1

dev_dependencies:
  flutter_launcher_icons: "^0.7.5"

flutter:
  assets:
    - assets/
    - assets/svg/bkk_bus.svg
    - assets/svg/bkk_night.svg
    - assets/svg/bkk_tram.svg
    - assets/svg/bkk_trolley.svg

    - assets/svg/artist.svg
    - assets/svg/budapest.svg
    - assets/svg/dot.svg
    - assets/svg/logo.svg
    - assets/svg/stop.svg
    - assets/svg/terminus.svg

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/font/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/font/OpenSans-Italic.ttf
          style: italic
        - asset: assets/font/OpenSans-Regular.ttf
    - family: RoadRage
      fonts:
        - asset: assets/font/RoadRage.ttf

flutter_icons:
  android: true
  ios: true
  image_path: "assets/appicon.png"
